package com.jobportal.dto;

public enum Intent {
    JOB_SEARCH,
    RESUME_ADVICE,
    INTERVIEW_QUESTIONS,
    SKILL_RECOMMENDATION,
    CAREER_GUIDANCE,
    RESUME_JOB_MATCH,
    CANDIDATE_SEARCH,
    GENERAL_CHAT,
    JOB_TREND_ANALYSIS,
    SALARY_INSIGHT,
    APPLICATION_HELP
}
